name: Demo with ssh
on: [pull_request]
jobs:
  build:
    name: Test ssh
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Scp
      run: |
        sudo apt-get install sshpass
        ls
        pwd
        sshpass -p 'Master@123' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r tf-models achinnak@ecegrid.ecn.purdue.edu:~/
    - name: Executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ecegrid.ecn.purdue.edu
        username: achinnak
        password: Master@123
        script: |
          rm -r testing
          cd
          mkdir testing
          mv ~/tf-models ~/testing/
          cd testing
          cd tf-models
          python3 -m official.vision.beta.projects.yolo.ops.box_ops_test
