name: SSH into VM with gcloud ssh
on: [push]
jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}

    - name: Start instace
      run: |
#        [ -d "/home/chinna/Projects/ci-prototype" ] && echo "Directory ~/.ssh exists."
#        mv id_rsa ~/.ssh
#        mv id_rsa.pub ~/.ssh
        rm -rf ~/.ssh/id_rsa
        rm -rf ~/.ssh/id_rsa.pub
        gcloud compute ssh ${{ secrets.INSTANCE_NAME }} --zone=europe-west4-a -- ls
        gcloud compute ssh ${{ secrets.INSTANCE_NAME }} --zone=europe-west4-a -- mkdir ~/testing
#        gcloud compute scp lowercase.py ${{ secrets.INSTANCE_NAME }}:~/testing --zone=europe-west4-a
#        gcloud compute ssh ${{ secrets.INSTANCE_NAME }} --zone=europe-west4-a --command="cd ~/testing && python3 -m pytest lowercase.py"