name: SSH into VM with gcloud ssh
on: [push]
jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}

    - name: Extract branch/repo name
      shell: bash
      id: vars
      run: |
        export BRANCH_NAME=$(echo ${GITHUB_REF##*/})
        export REPO_NAME=$(echo ${{ github.event.repository.name }})
        echo ${REPO_NAME}
        echo ${GITHUB_REPOSITORY}

#    - name: Start instace
#      run: |
#        gcloud compute instances list
#        gcloud compute ssh ${{ secrets.INSTANCE_NAME }} --zone=europe-west4-a

    - name: Run tests
      run: |
        gcloud compute ssh cam2tensorflow@${{ secrets.INSTANCE_NAME }} --zone=europe-west4-a --command="rm -rf ~/testing && mkdir ~/testing"
        gcloud compute ssh cam2tensorflow@${{ secrets.INSTANCE_NAME }} --zone=europe-west4-a --command="cd ~/testing && git clone git://github.com/${GITHUB_REPOSITORY}.git && ls"
        gcloud compute ssh cam2tensorflow@${{ secrets.INSTANCE_NAME }} --zone=europe-west4-a --command="cd ${REPO_NAME}/tf-models"
        gcloud compute ssh cam2tensorflow@${{ secrets.INSTANCE_NAME }} --zone=europe-west4-a --command="python3 -m official.vision.beta.projects.yolo.ops.box_ops_test"

#        gcloud compute scp --recurse tf-models cam2tensorflow@${{ secrets.INSTANCE_NAME }}:~/testing --zone=europe-west4-a
#        gcloud compute ssh ${{ secrets.INSTANCE_NAME }} --zone=europe-west4-a -- rm -rf testing && mkdir hey && ls
#        gcloud compute ssh ${{ secrets.INSTANCE_NAME }} --zone=europe-west4-a -- mkdir ~/testing
#        gcloud compute scp lowercase.py ${{ se        BRANCH_NAME=$(echo ${GITHUB_REF##*/})
        REPO_NAME=$(echo ${{ github.event.repository.name }})
        echo ${REPO_NAME}
        echo ${GITHUB_REPOSITORY}crets.INSTANCE_NAME }}:~/testing --zone=europe-west4-a
#        gcloud compute ssh ${{ secrets.INSTANCE_NAME }} --zone=europe-west4-a --command="cd ~/testing && python3 -m pytest lowercase.py"