name: Install Google Cloud SDK
on: [push]
jobs:
  build:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.PROJECT_NAME }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}

#    - name: Install Google Cloud SDK
#      run: |
#        curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-332.0.0-linux-x86_64.tar.gz
#        tar -C ~/ -zxvf google-cloud-sdk-332.0.0-linux-x86_64.tar.gz
#        gcloud auth activate-service-account --key-file ${{ secrets.SERVICE_ACCOUNT }}
#        ./google-cloud-sdk/bin/gcloud init --console-only --no-launch-browser
#        gcloud compute instances start
#        gcloud compute instances stop