name: Install Google Cloud SDK
on: [push]
jobs:
  build:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Google Cloud SDK
      run: |
        curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-332.0.0-linux-x86_64.tar.gz
        tar -C ~/ -zxvf google-cloud-sdk-332.0.0-linux-x86_64.tar.gz
        gcloud compute instances start odapi
        gcloud compute instances stop odapi