name: Start/Stop VM using gloud CLI
on: [push]
jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}

    - name: Start instace
      run: |
        gcloud compute instances list
        gcloud compute regions list
        gcloud compute zones list
        gcloud config get-value compute/region
        gcloud config get-value compute/zone
        gcloud compute instances start ${{ secrets.PROJECT_NAME }}
        gcloud compute instances stop ${{ secrets.PROJECT_NAME }}