name: SSH into VM
on: [push]
jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.VM_PRIVATE_KEY }}
        fingerprint: ${{ secrets.VM_FINGERPRINT }}
      script: |
      