name: TF sample test case
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r tf-models/official/requirements.txt
    - name: Test sample with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pip install tensorflow
        cd tf-models
        python -m official.vision.beta.projects.yolo.ops.box_ops_test