name: Test model with ssh
on: [pull_request]
jobs:
  build:
    name: Test ssh
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Scp
      run: |
        sudo apt-get install sshpass
        sshpass -p '' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null lowercase.py @ecegrid.ecn.purdue.edu:~/
        ls
    - name: Executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ecegrid.ecn.purdue.edu
        username:
        password:
        script: |
          rm -r testing
          python3 -m pip install pytest
          python3 -m pip install pytest-cov
          cd
          mkdir testing
          mv ~/lowercase.py ~/testing/
          cd testing
          ls -a
          echo "TESTING"
          python3 -m pytest lowercase.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
