name: test model with ssh
on: [pull_request]
jobs:
  build:
    name: Test ssh
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ecegrid.ecn.purdue.edu
        username: rheer
        password: 8rnyPU16ce
        script: |
          rm -r testing
          cd
          mkdir testing
          cd testing
          git clone git@github.com:ric-rhee/ci-prototype.git
          ls -a
          cd
